### ISSUE TITLE
GettingStarted: Deploying: bundlr CLI

### ISSUE THREAD

**Issue by DanMacDonald** [twilson63/permaweb-cookbook#11]
Similar in many ways to #10 

- Explain how bundlrCLI requires funding a bundlr up front, but all files succeed or fail atomically
- Example command for how to fund a bundlr from the CLI (explain confirmation times of various chains)
- Example command for deploying a folder from the CLI
- Explanation of how bundlr produces a manifest but does not deploy it by default

**Comment by twilson63** [comment]
Maybe mirror format like arkb example

**Comment by PBillingsby** [comment]
Handling in #43
