### ISSUE TITLE
hello-world(NodeJS) - guide a user to use NodeJS to publish data

### ISSUE THREAD

**Issue by twilson63** [twilson63/permaweb-cookbook#132]

**Comment by mogulx-operates** [comment]
I'm going to grab this one :)

**Comment by PBillingsby** [comment]
@mogulx-operates You still going to pick this up mate?

**Comment by mogulx-operates** [comment]
Yes. Luke and I have 2 guides that will be done over the next 2 weeks. (One next week for sure maybe 2)
