### ISSUE TITLE
kit(React): CRA should not be recommended

### ISSUE THREAD

**Issue by martonlederer** [twilson63/permaweb-cookbook#138]
In my opinion, create-react-app should not be recommended to anyone getting started with Arweave. 
- CRA provides an environment, that is significantly harder to configure than alternatives
- It is outaded and it has been unmainatined for 4+ months and it has been not recommended by the react community for years
- CRA uses outdated tools as well

Better alternatives exist:
- Vite
- Parcel
- Next.js (altho obviously, if it is deployed to a server, it is not decenralized. static generation is still a posibility)

**Comment by martonlederer** [comment]
PR #139 adds a Vite example to provide an alternative

**Comment by martonlederer** [comment]
I guess we can keep CRA there, but there should be more than one alternative guides listed there :D

**Comment by twilson63** [comment]
Yes we should have more than one for each framework I plan to do a Vite one for svelte tooSent from my iPhoneOn Jan 23, 2023, at 5:56 AM, Marton Lederer ***@***.***> wrote:﻿
I guess we can keep CRA there, but there should be more than one alternative guides listed there :D
