### ISSUE TITLE
CoreConcepts: SmartWeave Contracts

### ISSUE THREAD

**Issue by DanMacDonald** [twilson63/permaweb-cookbook#14]
What is the SmartWeave paradigm?
* Lazy Evaluation
* Original smartweave-js implementation
* Warp Contracts (by Redstone) implementation
* EXM (hosted execution)

Use cases
Scaling options

**Comment by atticusofsparta** [comment]
some primer material https://docs.google.com/document/u/0/d/1DT2s-CIieqvl-pJW8-1ESjKeP-eDlSjxL_-W0TCbIvI/mobilebasic

**Comment by atticusofsparta** [comment]
re: possible scaling options: Decentralized Execution Network (DEN), internal writes pattern using multiple contracts to avoid state bloat
