### ISSUE TITLE
chg(SWC-warp-deploy): Add a note about custom tags in the deploy guide

### ISSUE THREAD

**Issue by twilson63** [twilson63/permaweb-cookbook#170]
Let's add a note in the deploy guide how to provide custom tags to the deploy of a contract.

```
warp.createContract.deploy({
   ...
   tags: [{name: "Type", value: "video"}]
})
```

`tags: Record<string, string>[]`

**Comment by mrsaifullah52** [comment]
The deployment guide has been updated
