### ISSUE TITLE
chore: Auto deploy with Github Action 

### ISSUE THREAD

**Issue by twilson63** [twilson63/permaweb-cookbook#4]
Create a GitHub action that builds the project and deploys the project using arkb to the Permaweb, as well as updating the ANT contract to change the subdomain to the new TX_ID

**Comment by mogulx-operates** [comment]
This script deploys something and writes the `manifest_id` to a json file: https://github.com/permafacts/tools/blob/main/tools/scripts/perma-deploy.js

It's kind of ugly right now but the json file could be used for updating the ANT if there isn't anything else currently available :)  I can clean it up as well.

**Comment by twilson63** [comment]
@mogulx-operates 

Thank you for the code snippet,

Ended up going with bundlr-network/client and uploadDir

And posted the gh action! Works great!
