### ISSUE TITLE
Guide: testing with arLocal

### ISSUE THREAD

**Issue by twilson63** [twilson63/permaweb-cookbook#42]
Create a quick guide on how to test with arLocal, this guide would show how to programmatically launch arLocal, generate and mint a wallet, and how to mine a block.

> Warp creates helpers with wallet minting and block mining, but it maybe worth while to create code snippets for these actions, so that users can leverage the snippets to test their work.

> Also, it is worth noting that testing arLocal and using a L2 like bundlr.network will vary

**Comment by PBillingsby** [comment]
Added with #71
