### ISSUE TITLE
CoreConcepts: Posting a transaction

### ISSUE THREAD

**Issue by DanMacDonald** [twilson63/permaweb-cookbook#6]
Describe the different ways transactions get posted to arweave, include 3-5 lines of code for each example.

## L1 - Transactions
  - Posted using `arweave-js`,  are immediately available as "pending" but may drop.
## L2 Transactions
  - Posted via `bundlr-network/client`, guaranteed to confirm
## L2 Wallet Integration
  - `dispatch()` method of ArConnect and arweave.app wallets allow posting of <100KB transactions "for free"

**Comment by felwintrr** [comment]
Do you think we also need to distinguish a wallet-to-wallet transaction and a data transaction here?

**Comment by DanMacDonald** [comment]
I usually call the value transactions and data transactions, but data transactions can also transact value so the line between the two is always a little blurry.
