### ISSUE TITLE
CoreConcepts: Querying Arweave

### ISSUE THREAD

**Issue by DanMacDonald** [twilson63/permaweb-cookbook#7]
Querying via the arweave.net and goldsky GraphQL endpoints.

* Example of posting raw GraphQL using `fetch`
* Example using `ardb` 
* Example using `ar-gql`

Link to the GraphQL entry in the "References" section of the cookbook. (Work being tracked for the GraphQL entry item in #8 )

**Comment by twilson63** [comment]
NOTE: Identify `arql` deprecated functionality

**Comment by DanMacDonald** [comment]
Oh? whats that?

**Comment by twilson63** [comment]
arql is a legacy query functionality still embedded in arweave-js, but I don't think it works any longer.

**Comment by DanMacDonald** [comment]
oh funny, yes I remember ARQL. Just wasn't used to seeing it lower case like that 😅
