### ISSUE TITLE
References: GraphQL

### ISSUE THREAD

**Issue by DanMacDonald** [twilson63/permaweb-cookbook#8]
Important context for the reader.   
* GraphQL results are paginated
* There are rate limits for GraphQL queries at the gateway
* GrapgQL results include confirmed and pending transactions & how to differentiate them

Include the full GraphQL object schema for a transaction and list a couple common queries.  (by tag, by owner,. etc)

Include a link to https://gql-guide.arweave.dev/ as a reference for the full API.

**Comment by twilson63** [comment]
Maybe include learnings like where to go to learn graphql in general

**Comment by atticusofsparta** [comment]
Theres a pattern I started using for gql. Create a class that can take in a tag name and values, then the class takes care of things like exponential backoff, managing pagination, progress data fetching (get transaction list => query manifests for data) which is usefull for things like arfs which have alot of data not in tags but in the manifest itself. Might be a good snippet/pattern to include here.
