### ISSUE TITLE
GettingStarted: ArLocal

### ISSUE THREAD

**Issue by DanMacDonald** [twilson63/permaweb-cookbook#9]
A note about how TestWeave Docker is unmaintained and therefor largely deprecated.

ArLocal is a shim that mimics the Arweave blockchain locally without the overhead of running a full node.

Two modes of operation: 
 - Standalone `npx arlocal`
 - Inprocess ```import ArLocal from 'arlocal';```
 
Generating wallets and minting them tokens in `arlocal`

How to move pending transactions to confirmed with the `\mine` endpoint

Example of deploying a website or directory of files to `arlocal` using `arkb`

**Comment by PBillingsby** [comment]
Should I close this? @DanMacDonald

I feel as though majority of this will be covered in #42 

Unless you think an introduction would be helpful?

**Comment by twilson63** [comment]
Closed see #42
